//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalHealthAssistant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int Doc_Id { get; set; }
        public string Name { get; set; }
        public string Education { get; set; }
        public string Available_days { get; set; }
        public string Available_time { get; set; }
        public string Hospital { get; set; }
        public string Hospital_Address { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
        public string Phone_number { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Fees { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual User User { get; set; }
    }
}
