//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalHealthAssistant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Health_Vital
    {
        public int vital_Id { get; set; }
        public string Disease { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> BloodPressure_upper { get; set; }
        public Nullable<int> BloodPressure_lower { get; set; }
        public Nullable<int> Glucose_Levels { get; set; }
        public string Covid_Test { get; set; }
        public string Covid_Vaccine { get; set; }
        public string Other_Vaccine { get; set; }
        public string Other_Test { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string Image { get; set; }
    
        public virtual User User { get; set; }
    }
}
