//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalHealthAssistant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine_Dosage
    {
        public int Medicine_Id { get; set; }
        public string Medicine_name { get; set; }
        public string Times_in_a_Day { get; set; }
        public string Times_per_Week { get; set; }
        public string Dosage_Quantity { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual User User { get; set; }
    }
}
